---
storageDrivers:
- libstorage
libstorage:
  host: "127.0.0.1:1870"
  drivers:
  - ec2
  profiles:
    enabled: true
    client: false
    groups:
    - groupName=127.0.0.1
aws:
  accessKey: secretKey
  secretKey: accessKey
